Server:
  Port: 8903
  ReadTimeout: 15s
  WriteTimeout: 15s

API:
  BasePath: ""
  APITimeout: 15s
  EnableSwagger: true

Database:
  SlaveDSN: "clickhouse://default:changeme@localhost:19000/result"
  MasterDSN: "clickhouse://default:changeme@localhost:19000/result"
  RetryInterval: 10
  MaxIdleConn: 10
  MaxConn: 10
  ConnMaxLifetime: 10s

Kafka:
  Consumer:
    Brokers:
      - localhost:9092
    ClusterVersion: "3.2.0"
    ConsumerGroup: "result-service"
    MaxRetries: 3
    WorkerPoolSize: 5
    Retry:
      HandlerTimeout: 20s
      MaxRetry: 3
      RetryInitialDelay: 100ms
      MaxJitter: 500ms
      BackOffConfig:
        - 1m
        - 5m
        - 10m
  Topics:
    VoteSubmitData:
      Value: "votes.submit"
      ErrorHandler: "Phase1"
      WithBackOff: true
    VoteProcessed:
      Value: "votes.processed"
      ErrorHandler: "Phase1"
      WithBackOff: false
    VoteDLQ:
      Value: "votes.dlq"
      ErrorHandler: "Phase1"
      WithBackOff: false

GrpcServer:
  Port: 35001

Cors:
  AllowOrigins: "*"
  AllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
  AllowHeaders: "Content-Type,Authorization, X-User-Id, X-Role, X-Address, Ngrok-Skip-Browser-Warning"
  AllowCredentials: false
  ExposeHeaders: "X-Custom-Header"
  MaxAge: 3600